spring.application.name=ai-personal-finance-assistant
server.port=${SERVER_PORT:8080}

spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/personal_finance}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
